apiVersion: apps/v1
kind: Deployment
metadata:
  name: article-api-deployment
  labels:
    app: article-api
spec:
  replicas: 3
  selector:
    matchLabels:
      app: article-api
  template:
    metadata:
      labels:
        app: article-api
    spec:
      containers:
        - name: article-api
          image: iad.ocir.io/idaguzmb9zyu/artcile-api:v
          ports:
            - containerPort: 8080